# This workflow will build a .NET project
name: .NET CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - name: Check Out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Test solution
      run: dotnet test --no-build --logger "trx;LogFileName=result.trx" "Dummy.Tests/Dummy.Tests.csproj"

    - name: Report test results
      if: success() || failure()
      uses: dorny/test-reporter@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Unit-Test Results
        path: "Dummy.Tests/TestResults/net9.0/result.trx"
        reporter: "dotnet-trx"
        fail-on-error: true
